### ISSUE TITLE
accordion item not expanded when visible=true on init

### ISSUE THREAD

**Issue by soheilMohammadix** [coreui/coreui-angular#212]
- macOS 15.2
- Microsoft Edge v129.0.2792.65 (Official build) (arm64)
- I just cloned the latest version (5.3.5) and ran demo, but accordion item didn't expand. I saw this [commit](https://github.com/coreui/coreui-angular/commit/f2151e62584214a1d2fabdac421896b826de7f11)
but it wasn't fixed. could you please investigate it? 

Thanks in advance.

**Comment by xidedix** [comment]
@soheilMohammadix 
We cannot reproduce the issue here in a similar environment: macOS 15.2, 131.0.2903.112 (Official build) (arm64).

Please take a look here: https://stackblitz.com/edit/coreui-angular-accordion-vm1ylclz?file=src%2Fapp%2Fapp.component.html

Let us know if you’re still experiencing this problem.

**Comment by soheilMohammadix** [comment]
It was a problem on my end thanks.
but i do have the same problem with collapse and I couldn't fix it.
Could you please take a look here: https://stackblitz.com/edit/coreui-angular-accordion-vm1ylclz-chvkbyto?file=src%2Fapp%2Fapp.component.ts

**Comment by xidedix** [comment]
@soheilMohammadix, thanks for the heads up!
The collapse issue has been resolved in the `@coreui/angular` version `5.3.7`.

**Comment by soheilMohammadix** [comment]
I appreciate your consideration. 
It's fixed
